#!/bin/bash
loc=$(pwd)
cd ~

ln -sf ${loc}/.vimrc ./.vimrc
ln -sf ${loc}/.tmux.conf ./.tmux.conf
ln -sf ${loc}/.zshrc ./.zshrc
ln -sf ${loc}/.cshrc ./.cshrc
ln -sf ${loc}/.bashrc ./.bashrc
ln -sf ${loc}/.gitconfig ./.gitconfig
ln -sf ${loc}/.dir_colors ./.dir_colors
ln -sf ${loc}/.vim_dir ./.vim

git clone https://github.com/VundleVim/Vundle.vim.git ./.vim/bundle/Vundle.vim
vim +PluginInstall +qall
