#!/bin/bash
loc=$(pwd)
cd ~

ln -sf ${loc}/.vimrc ./.vimrc
ln -sf ${loc}/.tmux.conf ./.tmux.conf
ln -sf ${loc}/.zshrc ./.zshrc
ln -sf ${loc}/.cshrc ./.cshrc
ln -sf ${loc}/.bashrc ./.bashrc
ln -sf ${loc}/.gitconfig ./.gitconfig
